### ISSUE TITLE
default_cov_score.csv missing

### ISSUE THREAD

**Issue by xyloforce** [zhuweix/MethyladenosineFinder#1]
Hi,

I installed your pipeline as per your instructions and tried running it, but it fails at the ipd_analysis step with the file "default_cov_score.csv" missing. Since the path to this file is in "miniconda3/envs/maw/lib/python3.7/site-packages/MethyladenosineFinder-1.0.0-py3.7.egg/asset/default_cov_score.csv" perhaps the installation failed somehow. Could you give me indications where to find the file?
Thanks in advance ✨

**Comment by zhuweix** [comment]
It should be the src/asset/default_cov_score.csv file. I will check the code and see why it failed soon

**Comment by xyloforce** [comment]
Thanks a lot 😄

**Comment by zhuweix** [comment]
I fixed the bug. Please re-try the python setup.py install and tell me whether it worked for you now. You can always use the --scorefn parameter to use the src/asset/default_cov_score.csv
